services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tourplanner'
      - 'POSTGRES_PASSWORD=touradminpassword'
      - 'POSTGRES_USER=touradmin'
    ports:
      - "5432:5432"