spring.application.name=backend
server.port=8080
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/tourplanner
spring.datasource.username=touradmin
spring.datasource.password=touradminpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000
